services:
  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend-container
    ports:
      - "14000:5173"
  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    image: auth
    container_name: auth-container
    ports:
      - "15000:8000"
    env_file:
      - ./services/auth/app/.env
    depends_on:
      - db
volumes:
  postgres_data: