services:
  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend-container
    ports:
      - "14000:5173"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    env_file:
      - .env_pgadmin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - app-network

  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    image: auth
    container_name: auth-container
    ports:
      - "15000:8000"
    env_file:
      - ./services/auth/app/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  classes:
    build:
      context: ./services/classes
      dockerfile: Dockerfile
    image: classes
    container_name: classes-container
    ports:
      - "16000:8000"
    env_file:
      - ./services/classes/app/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  postgres_data:
  pgadmin-data:

networks:
  app-network:
    driver: bridge