services:
  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend-container
    ports:
      - "14000:5173"

  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    image: auth
    container_name: auth-container
    ports:
      - "15000:8000"
    env_file:
      - ./services/auth/app/.env
    depends_on:
      db:
        condition: service_healthy

  classes:
    build:
      context: ./services/classes
      dockerfile: Dockerfile
    image: classes
    container_name: classes-container
    ports:
      - "16000:8000"
    env_file:
      - ./services/classes/app/.env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: